### ISSUE TITLE
rsconf build error on fresh install

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#216]
```
rsconf (210-sirepo-sandbox)$ rsconf build
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/rsconf", line 33, in <module>
    sys.exit(load_entry_point('rsconf', 'console_scripts', 'rsconf')())
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/rsconf_console.py", line 17, in main
    return pkcli.main("rsconf")
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 148, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/pkcli/host.py", line 21, in init_docker_registry
    return _init_do(host, docker_registry)
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/pkcli/host.py", line 32, in _init_do
    return comp.host_init(dbt.host_db(c, h), h)
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/db.py", line 85, in host_db
    return self._host_db_fconf(*args) if cfg.fconf else self._host_db_jinja(*args)
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/db.py", line 113, in _host_db_fconf
    res.pkmerge(copy.deepcopy(v))
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 142, in pkmerge
    s.pkmerge(t, make_copy=False)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 142, in pkmerge
    s.pkmerge(t, make_copy=False)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 142, in pkmerge
    s.pkmerge(t, make_copy=False)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcollections.py", line 158, in pkmerge
    raise _type_err(k, s, t)
AssertionError: key=nameservers type mismatch between (self) base=['162.159.27.72', '162.159.24.39'] and to_merge={'RSCONF_DB_REPLACE': ['1.1.1.1', '1.0.0.1']}
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/rsconf", line 33, in <module>
    sys.exit(load_entry_point('rsconf', 'console_scripts', 'rsconf')())
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/rsconf_console.py", line 17, in main
    return pkcli.main("rsconf")
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 148, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/pkcli/build.py", line 109, in default_command
    setup_dev.default_command()
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/pkcli/setup_dev.py", line 102, in default_command
    subprocess.check_call(["rsconf", "host", "init_docker_registry", h])
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rsconf', 'host', 'init_docker_registry', 'v9.radia.run']' returned non-zero exit status 1.
```

**Comment by robnagler** [comment]
duplicate #215
