### ISSUE TITLE
build_test tries to do a chgrp which doesn't work over nfs

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/rsconf#312]

**Comment by rorour** [comment]
```
chgrp: changing group of '/home/vagrant/src/radiasoft/rsconf/tests/pkcli/build_work/1/srv-tmp/host-new/v3.radia.run/logrotate.sh': Operation not permitted
chgrp: changing group of '/home/vagrant/src/radiasoft/rsconf/tests/pkcli/build_work/1/srv-tmp/host-new/v3.radia.run': Operation not permitted
chgrp: changing group of '/home/vagrant/src/radiasoft/rsconf/tests/pkcli/build_work/1/srv-tmp/host-new': Operation not permitted
FAILED

=================================== FAILURES ===================================
__________________________________ test_build __________________________________
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/rsconf/tests/pkcli/build_test.py", line 25, in test_build
    build.default_command()
  File "/home/vagrant/src/radiasoft/rsconf/rsconf/pkcli/build.py", line 130, in default_command
    subprocess.check_call(["chgrp", "-R", db.cfg.srv_group, str(new_d)])
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['chgrp', '-R', 'vagrant', '/home/vagrant/src/radiasoft/rsconf/tests/pkcli/build_work/1/srv-tmp/host-new']' returned non-zero exit status 1.
============================== 1 failed in 5.10s ===============================
error: FAILED=1 passed=0
```
@robnagler any idea how to fix this? It happens over NFS because operations as root aren't permitted

**Comment by robnagler** [comment]
This is not running as root. The group is the current group so technically this is a no-op. However, production needs this feature. I don't think we want to add more in_dev_mode conditionals. It's just one more thing that can go wrong.

This is very specific to your dev environment. It's time to consider remote editing of files in PyCharm. Do you think you could try this?

**Comment by rorour** [comment]
I've got PyCharm working over ssh.
