### ISSUE TITLE
sirepo needs to poll rabbit at startup

### ISSUE THREAD

**Issue by robnagler** [radiasoft/rsconf#8]
sirepo needs to poll rabbitmq and only die after a couple of retries.

```text
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: SIGINT/SIGQUIT received...killing workers...
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: =WARNING REPORT==== 23-Feb-2018::03:34:04 ===
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: closing AMQP connection <0.14921.1> (216.17.132.38:43378 -> 216.17.132.38:5672):
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: client unexpectedly closed TCP connection
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: [2018-02-23 03:34:04,478: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: Traceback (most recent call last):
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/celery/worker/consumer.py", line 279, in start
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     blueprint.start(self)
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/celery/bootsteps.py", line 123, in start
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     step.start(parent)
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/celery/worker/consumer.py", line 838, in start
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     c.loop(*c.loop_args())
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/celery/worker/loops.py", line 76, in asynloop
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     next(loop)
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/kombu/async/hub.py", line 340, in create_loop
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     cb(*cbargs)
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/kombu/transport/base.py", line 164, in on_readable
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     reader(loop)
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/kombu/transport/base.py", line 146, in _read
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     drain_events(timeout=0)
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/amqp/connection.py", line 303, in drain_events
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     chanmap, None, timeout=timeout,
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/amqp/connection.py", line 366, in _wait_multiple
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     channel, method_sig, args, content = read_timeout(timeout)
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/amqp/connection.py", line 337, in read_timeout
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     return self.method_reader.read_method()
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:   File "/home/vagrant/.pyenv/versions/py2/lib/python2.7/site-packages/amqp/method_framing.py", line 189, in read_method
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:     raise m
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: error: [Errno 104] Connection reset by peer
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: [2018-02-23 03:34:04,497: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbitmq-alpha.sirepo.com:<port>//: [Errno 111] Connection refused.
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: Trying again in 2.00 seconds...
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]:
Feb 23 03:34:04 fnl6b.bivio.biz dockerd[14428]: worker: Warm shutdown (MainProcess)
Feb 23 03:34:05 fnl6b.bivio.biz dockerd[14428]: worker 1 buried after 1 seconds
Feb 23 03:34:05 fnl6b.bivio.biz dockerd[14428]: goodbye to uWSGI.
```

**Comment by robnagler** [comment]
Obsolete
